# theme.toml template for a Hugo theme
# See  https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "hugo-lines"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/easz/hugo-lines/master/LICENSE.md"
description = "A minimalistic Hugo blogging theme"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/easz/hugo-lines"

# If you have a running demo of the theme.
demosite = "https://lines-hugo-theme.netlify.app/"

tags = ["minimal", "blog"]
features = []

# If the theme has multiple authors
authors = [
  {name = "Ronalds Vilciņš", homepage = "https://www.ronaldsvilcins.com/"},
  {name = "easz", homepage = "https://github.com/easz/"}
]

# If porting an existing theme
[original]
    author = "Ronalds Vilciņš"
    homepage = "https://www.ronaldsvilcins.com/"
    repo = "https://github.com/ronv/lines"


[module]
  [module.hugoVersion]
    extended = true
